apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone
spec:
  replicas: 5
  selector:
      matchLabels:
        app.kubernetes.io/name: udacity-capstone
  template:
    metadata:
      labels:
        app.kubernetes.io/name: udacity-capstone
        app: web
    spec:
      containers:
      - name: udacity-capstone
        image: odira/udacity-capstone:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"